### ISSUE TITLE
Why does the result have committedBlocks instead of blob properties like blob, container, md5, etc?

### ISSUE THREAD

**Issue by raddevon** [Azure/azure-storage-node#100]
When I upload a largish file (35MB) to blob storage, I'm getting an unfamiliat result back in my `createBlockBlobFromLocalFile` callback. Instead of having the typical blob result properties, I get an object back with nothing but a single property: an array called `committedBlocks`.

I can see that the file was uploaded, but my app expects the blob name back in the callback. Why am I not getting this in the case of the larger file? I can't find any documentation about the result object and what its various properties mean.

**Comment by raddevon** [comment]
Tried passing options to increase the timeout thinking maybe if the timeout is too short, the method returns info about what was completed up to that point, but I'm getting the same result.

**Comment by yaxia** [comment]
@raddevon Thanks. This is an issue inside the library. We are working on the fix and will have it in a later release.

**Comment by vinjiang** [comment]
It's fixed in latest release (0.8.0), could you please have a try?

**Comment by tonytontian** [comment]
Hi I think the bug is still there for function createBlockBlobFromBrowser
