### ISSUE TITLE
QueueService.updateMessage is broken (mix of messagetext and messageText options)

### ISSUE THREAD

**Issue by jonasfj** [Azure/azure-storage-node#43]
The docs (well some of them) not sure which docs are official says it takes `messageText` the sample says `messagetext` the code uses both so that you have to provide both for anything to work :)

Check out:
https://github.com/Azure/azure-storage-node/blob/02b88267e063abc7a5ab330cf9a44cd5df97b9d1/lib/services/queue/queueservice.js#L1025-L1027

I suggest you go with `messageText` instead of `messagetext` :)

**Comment by slepox** [comment]
@jonasfj , this issue is fixed in latest release 0.4.3. Please check.

**Comment by jonasfj** [comment]
I didn't checkout `0.4.3` but assuming it's the code on master it appears the issue is still there:
https://github.com/Azure/azure-storage-node/blob/master/lib/services/queue/queueservice.js#L1043-L1045

Quick way to test is to open the link from and compare it to master...

```js
  if (options.messagetext) {
    content = QueueMessageResult.serialize(options.messageText, this.encodeMessage);
  }
```
should be:
```js
  if (options.messageText) { // <-- case sensitivity issue fix
    content = QueueMessageResult.serialize(options.messageText, this.encodeMessage);
  }
```

**Comment by slepox** [comment]
Sorry, not yet. will notify when the fix is in.

**Comment by yaxia** [comment]
Fixed in 0.5.0
